### ISSUE TITLE
Suggest:  Use sync function instead of async function when making decisions.

### ISSUE THREAD

**Issue by HermesYoung** [konnokai/Discord-Stream-Bot-Backend#1]
https://github.com/jun112561/Discord-Stream-Bot-Backend/blob/536bfc22f05654f726c3271e5b37f3b957c1940e/Discord%20Stream%20Bot%20Backend/Controllers/YouTubeMemberController.cs#L46 

As shown above, when you use an asynchronous function from StackExchange.Redis, requests do not send to Redis until the buffer is full or reaches a time limit. This may cause a delay in response when calling this API or returning a wrong response to the user.

**Comment by pierre0210** [comment]
> returning a wrong response to the user.

Is there any article or issue that can prove this problem exist?

**Comment by konnokai** [comment]
原則上應該是不會遇到Buffer吃滿的問題，數據量都很小而且也不會有狂登入的情況

**Comment by HermesYoung** [comment]
因為 StackExchange.Redis 要減少與 Redis 的連線次數, 在用 Async 函數時會先加到 buffer 裡而非直接送出
https://stackexchange.github.io/StackExchange.Redis/PipelinesMultiplexers#multiplexing

我後來才看到只有用在呼叫次數不高的 API ，目前看暫時不會有問題

**Comment by konnokai** [comment]
了解，感謝提醒，未來有遇到相關使用環境會注意這部分
